### PR TITLE
Improve gcr-auth by removing unnecessary commands

### PR DESCRIPTION
**Pull request by zackijack**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

after issue #19  is fixed (9de3d28), I think there are some commands that are no longer needed, so it can be simplified with just one command line.

### Description

When running `gcr-auth` we don't use sudo anymore, so the commands before and after are no longer needed. Also when running the gcr-auth folder `$HOME/.docker` will be automatically created.

### CODE REVIEW

**Comment by iynere** [comment]
thank you ! @zackijack I like the step name change, but I'm inclined to leave the rest of the code in place.... I realize it may typically be redundant, but we can't control what type of execution environment within which users might run this command..... depending on how a particular docker image's user / group permissions are configured, some of this logic may be necessary. but sounds like we can get rid of the `mkdir` line regardless, if that dir is automatically created. sound good ?

**Comment by zackijack** [comment]
@iynere sorry but I still don't understand why you still need run `chown` to current user when you run the `gcloud` command as the same user as the current user?

**Comment by iynere** [comment]
@zackijack what if the `.docker` directory already existed prior to running the command & was generated by a different user ? it's an edge case, but better to be safe than sorry here IMO

**Comment by zackijack** [comment]
I see. Thanks @iynere

**Pull request closed without merging**
