### PR TITLE
[semver:minor] Add attach-workspace option to Docker builds

### PR DESCRIPTION
**Pull request by Tybot204**
### Checklist

- [ x ] All new jobs, commands, executors, parameters have descriptions
- [ x ] Examples have been added for any significant new features
- [ x ] README has been updated, if necessary

### Motivation, issues

I have a step in CircleCI that validates my app builds correctly (Node.js based) and then saves the build to the workspace for other jobs to use. I would like to not have to rebuild my app during the Docker job. Docker needs access to this build data in the workspace to correctly build the container.

### Description

Added `attach-workspace` and `workspace-root` options to allow using workspace resources in Docker builds

### CODE REVIEW

**Comment by Tybot204** [comment]
Rebased with master and fixed the conflicts! Can merge after another review 😄

**Comment by gmemstr** [comment]
@Tybot204 Curious what your thoughts are on combining the bool and string parameters into one, so if we are passed a string (the path of the workspace), we then attach the workspace (since empty strings validate as false in conditions :) )

**Comment by Tybot204** [comment]
@gmemstr I could take it or leave it. The only downside to using the workspace root as the condition for attaching a workspace is requiring specifying the workspace path rather than just using the default. Either way works fine in my mind though!

**Comment by gmemstr** [comment]
@Tybot204 That is a good point - I wonder if leveraging our config logic so either can be defined would be helpful. Otherwise I'd rather stick to a single parameter that is blank by default

**Comment by gmemstr** [comment]
@Tybot204 Some conflicts to resolve, look relatively easy. After that I feel good merging this in.

**Review by gmemstr — APPROVED** [review]

**Pull request merged**
